// Generated by CoffeeScript 1.9.1
(function() {
    var exports;
  
    exports = module.exports = {
      version: '0.0.0',
      Model: require('./onem2m-model'),
      Http: require('./onem2m-http'),
      // Mqtt: require('./onem2m-mqtt')
    };
  
  }).call(this);
  